import type { EffectMeshParams, EffectMeshType } from './generators/effectMeshGenerator'

export const MESH_TYPE_OPTION_VALUES: ReadonlyArray<EffectMeshType> = [
  'slash',
  'arc',
  'openCylinder',
  'arcRibbon',
  'ribbon',
  'lightningRibbon',
  'risingSpiralRibbon',
  'cylinderSpiralRibbon',
  'plane',
  'flatRing',
  'sphere',
  'hemisphere',
  'zHemisphere',
  'beamDome',
  'honeycombPlane',
  'honeycombRadialPlane',
  'honeycombSphere',
]

const MESH_TYPE_TEMPLATE_PARAMS: Record<EffectMeshType, EffectMeshParams> = {
  slash: {
    divisions: 12,
    widthDivisions: 2,
    thickness: 0.5,
    length: 3,
    curve: 0.8,
    topCurve: 0.2,
    taper: 0.35,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  ribbon: {
    divisions: 24,
    widthDivisions: 2,
    thickness: 0.35,
    length: 4,
    curve: 0.8,
    topCurve: 0.2,
    taper: 0.15,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  lightningRibbon: {
    divisions: 24,
    widthDivisions: 1,
    thickness: 0.22,
    length: 5,
    curve: 1.4,
    topCurve: 0,
    taper: 0.75,
    spread: 0.25,
    twist: 0,
    waveCount: 5,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  arc: {
    divisions: 12,
    widthDivisions: 2,
    thickness: 0.8,
    length: 1.5,
    curve: 1.1,
    topCurve: 0.3,
    taper: 0,
    spread: 0.1,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  arcRibbon: {
    divisions: 12,
    widthDivisions: 2,
    thickness: 0.2,
    length: 1.5,
    curve: 1,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0.5,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  spiral: {
    divisions: 32,
    widthDivisions: 2,
    thickness: 0.3,
    length: 3,
    curve: 1.2,
    topCurve: 0.2,
    taper: 0.25,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  risingSpiralRibbon: {
    divisions: 32,
    widthDivisions: 2,
    thickness: 0.35,
    length: 5,
    curve: 1.2,
    topCurve: 0.2,
    taper: 0.25,
    spread: 0.7,
    twist: 0.4,
    waveCount: 3,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  cylinderSpiralRibbon: {
    divisions: 32,
    widthDivisions: 2,
    thickness: 0.35,
    length: 5,
    curve: 1,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 3,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  burst: {
    divisions: 16,
    widthDivisions: 8,
    thickness: 0.5,
    length: 3,
    curve: 1,
    topCurve: 0.2,
    taper: 0.4,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  plane: {
    divisions: 1,
    widthDivisions: 1,
    thickness: 2,
    length: 2,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  honeycombPlane: {
    divisions: 6,
    widthDivisions: 8,
    thickness: 3,
    length: 4,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0.08,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
    honeycombUvMode: 'layout',
    honeycombExtraOffsetRows: false,
    honeycombXCurve: 0,
    honeycombRandomRemoval: 0,
  },
  honeycombRadialPlane: {
    divisions: 4,
    widthDivisions: 1,
    thickness: 3,
    length: 3,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0.08,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
    honeycombUvMode: 'layout',
    honeycombCenterRingRemoval: 0,
    honeycombXCurve: 0,
    honeycombRandomRemoval: 0,
  },
  honeycombSphere: {
    divisions: 4,
    widthDivisions: 1,
    thickness: 1,
    length: 3,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0.08,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
    honeycombUvMode: 'layout',
    honeycombRandomRemoval: 0,
  },
  flatRing: {
    divisions: 32,
    widthDivisions: 1,
    thickness: 0.5,
    length: 3,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  sphere: {
    divisions: 16,
    widthDivisions: 4,
    thickness: 1,
    length: 2,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  hemisphere: {
    divisions: 12,
    widthDivisions: 4,
    thickness: 1,
    length: 2,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  zHemisphere: {
    divisions: 12,
    widthDivisions: 4,
    thickness: 1,
    length: 2,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  openCylinder: {
    divisions: 2,
    widthDivisions: 12,
    thickness: 1,
    length: 0.3,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0.5,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
  },
  beamDome: {
    divisions: 5,
    widthDivisions: 8,
    thickness: 1,
    length: 4,
    curve: 0,
    topCurve: 0,
    taper: 0,
    spread: 0,
    twist: 0,
    waveCount: 1,
    seed: 0,
    yClip: 0,
    cylinderScale: 1,
    cylinderDivisions: 2,
  },
}

export const getMeshTypeTemplateParams = (meshType: EffectMeshType): EffectMeshParams => {
  const params = MESH_TYPE_TEMPLATE_PARAMS[meshType]
  return { ...params, endTaper: params.endTaper ?? params.taper }
}

export const getMeshTypeTemplateOptions = (meshType: EffectMeshType) => ({
  mirrorZ: meshType === 'arc',
  doubleSided: false,
  crossMesh: false,
})
